// This file is intentionally left blank.
// The Firebase configuration will be provided at runtime.
// DO NOT EDIT THIS FILE.
export const firebaseConfig = {
  apiKey: "AIzaSyB-...",
  authDomain: "...",
  projectId: "...",
  storageBucket: "...",
  messagingSenderId: "...",
  appId: "...",
};
